[package]
name = "ML_ALGO_Rewite"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray="0.15"
ndarray-rand="0.14"
csv="1.3"
serde={version="1.0",features=["derive"]}
serde_json="1.0"
rand="0.8"
